# Server
server.port=8080

# Logging Levels
logging.level.root=INFO
logging.level.com.example.logging.controller=DEBUG
logging.level.com.example.logging.service=TRACE

# Actuator Exposure
management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=always

# Application Info
info.app.name=Logging & Monitoring Demo
info.app.version=1.0.0
info.app.description=Spring Boot Logging & Actuator Project
